/**
 * @tokenproof/canton-sdk
 * TypeScript SDK for the TokenProof Canton compliance primitive.
 *
 * Current (M1-M3): wraps the TokenProof FastAPI backend via axios.
 * M4: @c7/ledger (NOT the deprecated @daml/ledger) wired for direct gRPC Ledger API
 *     access and streamProofEvents. DAML bindings generated by: dpm codegen-alpha-typescript
 *
 * Primary methods:
 *   evaluateAsset      — submit asset metadata for classification + on-ledger anchoring
 *   getProofStatus     — query live ComplianceProof status from Active Contract Service
 *   verifyProof        — recompute proof hash and compare with on-ledger record
 *   streamProofEvents  — subscribe to proof lifecycle events via gRPC Ledger API (M4 stub)
 */

import axios, { AxiosInstance } from "axios";

// DecisionStatus mirrors the DAML type in Main.Types
export type DecisionStatus = "Active" | "Suspended" | "Revoked";

export interface AssetMetadata {
  [key: string]: unknown;
}

export interface EvaluateAssetOptions {
  assetId: string;
  issuerParty: string;
  policyPack: "GENIUS_v1" | "CLARITY_v1" | "SEC_CLASSIFICATION_v1";
  assetMetadata: AssetMetadata;
  regulatorParty?: string;
  anchorOnLedger?: boolean;
}

export interface ControlResult {
  control: string;
  passed: boolean;
  reason: string | null;
}

export interface EvaluationResult {
  assetId: string;
  classification: string;
  policyVersion: string;
  passed: boolean;
  controlResults: ControlResult[];
  proofHash: string;
  timestamp: string;
}

export interface LedgerAnchorResult {
  success: boolean;
  contractId?: string;
  error?: string;
}

export interface EvaluateAssetResult {
  evaluation: EvaluationResult;
  ledger: LedgerAnchorResult | null;
}

export interface ProofStatus {
  contractId: string;
  assetId: string;
  classification: string;
  policyVersion: string;
  decisionStatus: DecisionStatus;
  proofHash: string;
  timestamp: string;
}

export interface VerifyProofResult {
  assetId: string;
  verified: boolean;
  onLedgerHash: string;
  recomputedHash: string;
  note: string;
}

export interface ProofEvent {
  type: "SuspendProof" | "RevokeProof" | "ReEvaluate";
  assetId: string;
  previousStatus: DecisionStatus;
  newStatus: DecisionStatus;
  actingParty: string;
  occurredAt: string;
}

export interface TokenProofClientConfig {
  backendUrl: string;
  grpcUrl?: string;
}

/**
 * TokenProofClient — main entry point for the SDK.
 * Wraps the FastAPI backend for classification and proof lifecycle operations.
 */
export class TokenProofClient {
  private readonly http: AxiosInstance;
  private readonly grpcUrl: string;

  constructor(config: TokenProofClientConfig) {
    this.http = axios.create({
      baseURL: config.backendUrl,
      timeout: 30_000,
      headers: { "Content-Type": "application/json" },
    });
    this.grpcUrl = config.grpcUrl ?? "localhost:6866";
  }

  /**
   * Submit an asset for classification and optionally anchor the proof on Canton.
   * POST /evaluate
   */
  async evaluateAsset(options: EvaluateAssetOptions): Promise<EvaluateAssetResult> {
    const response = await this.http.post<EvaluateAssetResult>("/evaluate", {
      assetId:        options.assetId,
      issuerParty:    options.issuerParty,
      policyPack:     options.policyPack,
      assetMetadata:  options.assetMetadata,
      regulatorParty: options.regulatorParty ?? null,
      anchorOnLedger: options.anchorOnLedger ?? true,
    });
    return response.data;
  }

  /**
   * Query the live ComplianceProof status for an asset.
   * Proof status is never cached — always read from the Active Contract Service.
   * GET /proof/{assetId}
   */
  async getProofStatus(assetId: string, issuerParty: string): Promise<ProofStatus> {
    const response = await this.http.get<ProofStatus>(`/proof/${assetId}`, {
      params: { issuer_party: issuerParty },
    });
    return response.data;
  }

  /**
   * Recompute the proof hash from raw metadata and compare with the on-ledger record.
   * Returns verified=true only if the hashes match exactly.
   * POST /verify
   */
  async verifyProof(
    assetId: string,
    issuerParty: string,
    proofHash: string,
    policyPack: EvaluateAssetOptions["policyPack"],
    assetMetadata: AssetMetadata,
  ): Promise<VerifyProofResult> {
    const response = await this.http.post<VerifyProofResult>("/verify", {
      assetId,
      issuerParty,
      proofHash,
      policyPack,
      assetMetadata,
    });
    return response.data;
  }

  /**
   * Subscribe to proof lifecycle events via the gRPC Ledger API (port 6866).
   *
   * Not yet implemented — ships in milestone M4 with @c7/ledger gRPC bindings
   * generated by `dpm codegen-alpha-typescript`. Throws to avoid the silent
   * no-op failure mode where consumers wait forever for events that never fire.
   *
   * Until M4, poll getProofStatus() on a short interval to detect lifecycle
   * transitions in production code.
   */
  streamProofEvents(
    _assetId: string,
    _callback: (event: ProofEvent) => void,
  ): () => void {
    throw new Error(
      "TokenProofClient.streamProofEvents is not implemented yet. " +
      "Ships in milestone M4 with @c7/ledger gRPC bindings. " +
      "Until then, poll getProofStatus() to detect lifecycle transitions."
    );
  }
}

// Convenience factory for the most common configuration.
export function createTokenProofClient(backendUrl: string, grpcUrl?: string): TokenProofClient {
  return new TokenProofClient({ backendUrl, grpcUrl });
}

// Named re-exports for tree-shaking convenience.
export { EvaluateAssetOptions as EvaluateOptions };
